In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[3.7386e-14, 6.6532e-33, 1.8337e+31],
        [1.3556e-19, 1.8370e+25, 2.0616e-19],
        [4.7429e+30, 7.4908e+11, 1.9438e-19],
        [1.2123e+25, 3.9666e-11, 1.5768e-19],
        [1.9432e-19, 1.8390e+25, 1.9346e-19]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1259, 0.8402, 0.1846],
        [0.8965, 0.8682, 0.6564],
        [0.7762, 0.3202, 0.2155],
        [0.3639, 0.1203, 0.5158],
        [0.5032, 0.0045, 0.5701]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.3, 4])
print(x)

tensor([5.3000, 4.0000])


In [10]:
x = x.new_zeros(5, 3, dtype=torch.double)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [11]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.2095,  0.8644, -1.9426],
        [ 1.7118,  1.3711,  1.6198],
        [-1.7528,  0.0934,  1.1297],
        [-1.0272, -1.8422, -0.7585],
        [ 0.2804, -0.5449,  0.4083]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [15]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.1074,  1.7448, -1.8002],
        [ 2.7090,  1.9457,  1.7788],
        [-1.2147,  0.2421,  1.6358],
        [-0.9231, -1.7543,  0.1858],
        [ 1.0727, -0.0673,  1.3656]])


In [16]:
print(torch.add(x, y))

tensor([[-1.1074,  1.7448, -1.8002],
        [ 2.7090,  1.9457,  1.7788],
        [-1.2147,  0.2421,  1.6358],
        [-0.9231, -1.7543,  0.1858],
        [ 1.0727, -0.0673,  1.3656]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.1074,  1.7448, -1.8002],
        [ 2.7090,  1.9457,  1.7788],
        [-1.2147,  0.2421,  1.6358],
        [-0.9231, -1.7543,  0.1858],
        [ 1.0727, -0.0673,  1.3656]])


In [19]:
y.add_(x)
print(y)

tensor([[-1.1074,  1.7448, -1.8002],
        [ 2.7090,  1.9457,  1.7788],
        [-1.2147,  0.2421,  1.6358],
        [-0.9231, -1.7543,  0.1858],
        [ 1.0727, -0.0673,  1.3656]])


In [20]:
x.copy_(y)
print(x)

tensor([[-1.1074,  1.7448, -1.8002],
        [ 2.7090,  1.9457,  1.7788],
        [-1.2147,  0.2421,  1.6358],
        [-0.9231, -1.7543,  0.1858],
        [ 1.0727, -0.0673,  1.3656]])


In [21]:
print(x[:, 1])

tensor([ 1.7448,  1.9457,  0.2421, -1.7543, -0.0673])


In [22]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x = torch.randn(2)
print(x)
print([i.item() for i in x])

tensor([0.4467, 1.3573])
[0.44671162962913513, 1.3572906255722046]


In [50]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [51]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [54]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.4467, 2.3573], device='cuda:0')
tensor([1.4467, 2.3573], dtype=torch.float64)


In [56]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [57]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [58]:
print(y.grad_fn)

In [59]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [60]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [61]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [62]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([-634.5884,  430.9149, -825.2819], grad_fn=<MulBackward0>)


In [63]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [64]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [65]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


# NEURAL NETWORKS

In [87]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        # 1 input channel, 6 output channels, 3x3 suquare convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)
    

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [70]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 3, 3])


In [88]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0978,  0.0805, -0.0758, -0.0881,  0.1381, -0.0949, -0.0888,  0.0287,
          0.0338, -0.0279]], grad_fn=<AddmmBackward>)


In [89]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [90]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(0.3880, grad_fn=<MseLossBackward>)


In [96]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [100]:
net.zero_grad()
print("conv1.bias.grad before backward")
print(net.conv1.bias.grad)

loss.backward()
print("conv1.bias.grad after backward")
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])


RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [101]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [102]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in training loop:
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()